// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TestingAllergy</b><br>
 * Generated     : <b>2015/10/27 8:32:02 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  October 27, 2015
 * @author ap028084
 */
public abstract class TestingAllergyHelper extends RationalTestScript
{
	/**
	 * Add: with default state.
	 *		.text : Add
	 * 		.class : .Pushbutton
	 * 		.name : Add
	 * 		.classIndex : 0
	 */
	protected GuiTestObject addbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("addbutton"));
	}
	/**
	 * Add: with specific test context and state.
	 *		.text : Add
	 * 		.class : .Pushbutton
	 * 		.name : Add
	 * 		.classIndex : 0
	 */
	protected GuiTestObject addbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("addbutton"), anchor, flags);
	}
	
	/**
	 * MenuBar: with default state.
	 *		.text : Menu Bar
	 * 		.class : .Menubar
	 * 		.name : Menu Bar
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject menuBarmenuBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("menuBarmenuBar"));
	}
	/**
	 * MenuBar: with specific test context and state.
	 *		.text : Menu Bar
	 * 		.class : .Menubar
	 * 		.name : Menu Bar
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject menuBarmenuBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("menuBarmenuBar"), anchor, flags);
	}
	
	

	protected TestingAllergyHelper()
	{
		setScriptName("TestingAllergy");
	}
	
}

